### ISSUE TITLE
HELP Nzyme Failed to Start

### ISSUE THREAD

**Issue by RichardPhilipsRoy** [lennartkoopmann/nzyme#48]

**Comment by kairat1115** [comment]
Tried to run on debian 9.9, Kali 2019.2, Ubuntu 18.04, but without any success

Here is log:

user@nzyme:~/Documents$ sudo java -jar nzyme-0.2.1.jar --debug -c /etc/nzyme/nzyme.conf
10:41:29.744 [main] INFO  horse.wtf.nzyme.Main - Version: 0.2.1 built at [2018-06-24T19:27:46Z].
10:41:29.804 [main] INFO  horse.wtf.nzyme.Main - Printing statistics every 60 seconds.
10:41:30.249 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [Versionchecks] for every <60 MINUTES> with <0 MINUTES> initial delay.
10:41:30.250 [periodicals-0] INFO  horse.wtf.nzyme.periodicals.Periodical - Running periodical [Versionchecks].
10:41:30.252 [periodicals-0] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Starting to check for most recent Nzyme version.
10:41:30.274 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
10:41:30.276 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
10:41:30.287 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
10:41:30.287 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
10:41:30.288 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
10:41:30.288 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
10:41:30.289 [main] DEBUG io.netty.util.internal.PlatformDependent - Java version: 8
10:41:30.289 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
10:41:30.289 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
10:41:30.290 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
10:41:30.291 [main] DEBUG io.netty.util.internal.PlatformDependent - Javassist: unavailable
10:41:30.291 [main] DEBUG io.netty.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
10:41:30.291 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
10:41:30.291 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
10:41:30.292 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
10:41:30.304 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
10:41:30.305 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
10:41:30.330 [main] DEBUG io.netty.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xb87a1664f76b92b3 (took 0 ms)
10:41:30.377 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
10:41:30.377 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
10:41:30.396 [gelfTcpTransport-1-1] DEBUG org.graylog2.gelfclient.transport.GelfTcpTransport - Connected!
10:41:30.793 [main] INFO  horse.wtf.nzyme.Nzyme - Building PCAP handle on interface [wlx00c0caa6567f]
10:41:30.823 [main] ERROR horse.wtf.nzyme.Main - Boot error.
horse.wtf.nzyme.NzymeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.NzymeImpl.<init>(NzymeImpl.java:128) ~[nzyme-0.2.1.jar:?]
        at horse.wtf.nzyme.Main.main(Main.java:114) [nzyme-0.2.1.jar:?]
Caused by: org.pcap4j.core.PcapNativeException: wlx00c0caa6567f: SIOCGIWPRIV: Argument list too long
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-0.2.1.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:47) ~[nzyme-0.2.1.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1671) ~[nzyme-0.2.1.jar:?]
        at horse.wtf.nzyme.NzymeImpl.<init>(NzymeImpl.java:122) ~[nzyme-0.2.1.jar:?]
        ... 1 more
10:41:30.828 [shutdown-hook] INFO  horse.wtf.nzyme.Main - Shutting down.

Java: 
user@nzyme:~/Documents$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

Libpcap:
libpcap0.8 is already the newest version (1.8.1-6ubuntu1).
