### ISSUE TITLE
Reverse Proxying not working correctly

### ISSUE THREAD

**Issue by cd4046bf** [lennartkoopmann/nzyme#752]
I'm running nzyme behind a apache2 reverse proxy under a subdirectory so I set
rest_listen_uri: "http://127.0.0.1:22900/nzyme/"
http_external_uri: "https://domain/nzyme/"
in the nzyme config.
The reverse proxy works, but the web interface does not load completely and the internal links in the web interface are based of / and not /nzyme/ so they dont work.
Is this a setup issue or an issue with nzyme?

**Comment by lennartkoopmann** [comment]
This is expected behavior because nzyme does currently not support any other path than `/` to be running under. Can you use a subdomain instead? Something like `nzyme.example.com` instead of `example.com/nzyme`?

**Comment by cd4046bf** [comment]
I can use a different port for nzyme and use it separate from my reverse proxy. I wanted to use a reverse proxy, because i had multiple services under different subdirectories on the apache server. Is support for running nzyme in a subdirectory planned?

**Comment by lennartkoopmann** [comment]
Sure, that is another good idea!

There are currently no plans for subdirectory support because it's not a common deployment I've seen so far. We built it in Graylog a while back and it's more work than it appears to be in the beginning. 😂 You can file a separate feature request and maybe others vote for it!

**Comment by cd4046bf** [comment]
Ok thanks
